name: Compile, test and deploy
on: [ push ]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo date
        run: echo "Current time is $(date)"
      - name: check out code
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Cache maven files
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: setup maven 
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - name: run test
        if: ${{ !contains(github.event.head_commit.message, 'skip test') }}
        run: mvn clean verify
      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true